### PR TITLE
Missing Dates in Dashboard Statistics Fix

### LINKED ISSUE #172: Missing dates/times between data points
We need to fill data points with the missing dates/time even if we have 0 impressions / spent there
Currently no data point is drawn if there is no impressions

### PR DESCRIPTION
**Pull request by rori4**
- fixes Missing dates/times between data points (closes #172)

### CODE REVIEW

File: src/helpers/timeHelpers.js [hunk 1]
```diff
@@ -43,4 +58,37 @@ export const intervalsMs = {
...
+	}
+	const newAggr = []
+	for (
+		var m = moment(time.interval.start);
+		m.diff(time.interval.end, time.step.unit) <= 0;
+		m.add(time.step.ammount, time.step.unit)
+	) {
+		newAggr.push({ value: '0', time: m.unix() * 1000 })
+	}
+	const result = newAggr.map((item, i) => Object.assign({}, item, prevAggr[i]))
```
Comment (Ivshti) [inline src/helpers/timeHelpers.js]: can't use the spread operator rather than `Object.assign` ?

**Review by Ivshti — CHANGES_REQUESTED** [review]

File: src/helpers/timeHelpers.js (hunk 1 above)
Comment (rori4) [reply src/helpers/timeHelpers.js]: yes it would be better. don't know why I used the obj assign

**Review by ivopaunov — APPROVED** [review]
