### PR TITLE
Getting Started Guide With Tutorials & Translation Update

### LINKED ISSUE #366: Chart Last Datapoint Labels Skipped
**Describe the bug**
The last datapoints in the chart is skipped
missing datapoint

**To Reproduce**
1. Go to the chart on daily
2. See missing datapoints at the end

### PR DESCRIPTION
**Pull request by rori4**
- UX: getting started guide #79 (This adds all the steps except the bonus one which is blocked from the relayer)
- ~~added components mapping to translations. Not you can add components tot `t('TRANSLATE", {components: [ <Comp1/>, <Comp2/>]})`. Currently nesting components is not supported~~
- added all the tutorials as well
- fiexes Chart Last Datapoints Skipped (closes #366)

paunov:
- added sensitization for translatiosn 
- translate - just pass component as with args and it will work. To use translations with tags (\<strong> etc...) need to use it with `dangerouslySetInnerHTML`
- misc fixes

### CODE REVIEW

File: src/components/confirm/Confirm.js [hunk 1]
```diff
@@ -55,9 +55,10 @@ export class Confirm extends Component {
 			<Dialog open={this.state.active}>
 				<DialogTitle id='alert-dialog-title'>{title}</DialogTitle>
 				<DialogContent>
-					<DialogContentText id='alert-dialog-description'>
```
Comment (rori4) [inline src/components/confirm/Confirm.js]: This is commented out because with the translation with components it gives errors as this is a `<p>` tag

File: src/components/dashboard/charts/simplified.js [hunk 2]
```diff
@@ -127,6 +127,12 @@ export const SimpleStatistics = ({
 						display: true,
 						labelString: t(xLabel || 'TIMEFRAME'),
 					},
+					ticks: {
+						autoSkip: false,
+						callback: function(tick, index, array) {
```
Comment (rori4) [inline src/components/dashboard/charts/simplified.js:132]: This fixes the last data points that are missing 
missing datapoint

File: src/components/common/anchor/anchor.js [hunk 3]
```diff
@@ -10,22 +11,43 @@ const getUrl = url => {
...
 			href={url}
-			style={{ wordBreak: 'break-all' }} // TODO: add it where needed only
+			style={{ wordBreak: 'break-all', ...style }} // TODO: add it where needed only
 		>
 			{children || label}
 		</Link>
 	)
 }
 
+export const ExternalAnchor = ({ href, children, style }) => (
```
Comment (ivopaunov) [inline src/components/common/anchor/anchor.js:45]: The main reason for this component to exist is because of the external links.
When you make "ExternalAnchor" be sure there is attribute ```rel='noopener noreferrer'```

File: src/selectors/accountSelectors.js [hunk 4]
```diff
@@ -74,6 +84,16 @@ export const selectAccountIdentityRoutineAuthTuple = createSelector(
...
 )
 
+export const selectAccountIdentityDeployData = createSelector(
+	selectAccountIdentity,
+	({ relayerData }) => relayerData.deployData
+)
+
+export const selectChannelsWithUserBalances = createSelector(
+	selectChannels,
+	({ withBalance }) => withBalance || {}
```
Comment (ivopaunov) [inline src/selectors/accountSelectors.js]: It doesn't work any more use `selectChannelsWithUserBalancesEligible`

File: src/services/translations/translations.js [hunk 5]
```diff
@@ -21,9 +22,38 @@ const interpolate = (tpl, args) => {
 	})
 }
 
+const addComponents = (tpl, components) => {
```
Comment (ivopaunov) [inline src/services/translations/translations.js]: Don't not do this. If you want component in the translations, add the components in the translations strings and sanitize them here.
I can help with that if you want.

File: src/components/confirm/Confirm.js (hunk 1 above)
Comment (ivopaunov) [reply src/components/confirm/Confirm.js]: see the comment for adding components to translations

File: src/components/dashboard/dashboard/Dashboard.js [hunk 6]
```diff
@@ -125,6 +127,7 @@ function Dashboard(props) {
 			// because of the campaigns table data update fix
 			await analyticsCampaignsLoop.start()
 			campaignsLoop.start()
+			setDataLoaded(true)
```
Comment (ivopaunov) [inline src/components/dashboard/dashboard/Dashboard.js:135]: I'm not sure but maybe you need to `await` campaigns loop as well.

**Review by ivopaunov — CHANGES_REQUESTED** [review]
